apiVersion: apps/v1
kind: Deployment
metadata:
  name: hleng99
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hleng99
  template:
    metadata:
      labels:
        app: hleng99
    spec:
      containers:
      - image: okteto.dev/hleng99:latest
        name: hleng99
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e8a9637d-442b-467f-a27f-fa5dc7a58fbf"
        - name: Vless_Path
          value: "/vl56fd555"
        - name: Vmess_UUID
          value: "e8a9637d-442b-467f-a27f-fa5dc7a58fbf"
        - name: Vmess_Path
          value: "/vm6re666"
        - name: Share_Path
          value: "/v2link"
