apiVersion: v1
kind: Service
metadata:
  name: hleng99
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hleng99"
    port: 8080
  selector:
    app: hleng99
